### ISSUE TITLE
Make Profile Pic Responsive 

### ISSUE THREAD

**Issue by Anshul1507** [Anshul1507/simple-portfolio#1]
Currently profile pic is distorting at smaller size screen. Make it response for all types of screens.

**Comment by codewizard26** [comment]
can i make some contribution for the same

**Comment by Anshul1507** [comment]
Sorry man, but this one is reserved for one of my friend, he told me to mention this issue so he can start work on this.

**Comment by Anshul1507** [comment]
Be there @codewizard26 , I will create new issues on the same repo in a while. 😀

**Comment by constant-variable** [comment]
Yes, @Anshul1507 i guess you should assign this to me before someone else approaches for the same. 👍

**Comment by Anshul1507** [comment]
Sure @constant-variable 💯

**Comment by codewizard26** [comment]
hey i already did

**Comment by Anshul1507** [comment]
Dear @codewizard26, you have to wait till I assigns you this work.

**Comment by codewizard26** [comment]
Best of luck 👍

**Comment by Gimenz** [comment]
Can you add hacktoberfest label to rhis repo? And assigns me :D

**Comment by Anshul1507** [comment]
@Gimenz i cant assign more than one. let @constant-variable solve the issue

**Comment by ayush-AI** [comment]
can i work on this. If it's not solved.

**Comment by Anshul1507** [comment]
It is solved in recent pull request @ayush-AI. 👍
